### PR TITLE
Update libs

### PR DESCRIPTION
**Pull request by otopba**

### CODE REVIEW

**Comment by timrijckaert** [comment]
I want to wait a bit with the upgrade to the latest Gradle tools, we had some issue with it when implementing it in the app which uses flavors and appbundles

**Comment by otopba** [comment]
What kind of issues do you have?

**Comment by timrijckaert** [comment]
https://github.com/flutter/flutter/pull/39126

**Comment by otopba** [comment]
I think new Flutter release contains fixes for this
https://github.com/flutter/flutter/wiki/Release-Notes-Flutter-1.9.1

**Comment by timrijckaert** [comment]
It has been fixed but it is not on stable yet.

**Comment by otopba** [comment]
@timrijckaert 
Hi!
Why you are not merge it?

**Comment by timrijckaert** [comment]
I opened up a new PR with combined changes of multiple open PR's take a look https://github.com/vrtdev/flutter_workmanager/pull/128

**Comment by otopba** [comment]
@timrijckaert  Ok thank you!

**Pull request closed without merging**
